#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DPI_OPTIONS { 600, 900, 1200, 1600, 2400 }
#define PLOOPY_DPI_DEFAULT 1
#define PLOOPY_DRAGSCROLL_DIVISOR_H 16.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 16.0

#define PD_JIGGLER_BACKOFF 10
#define PD_JIGGLER_PATTERN PD_JIGGLER_PATTERN_SUBTLE
#define PD_JIGGLER_PATTERN_INTRO PD_JIGGLER_PATTERN_YLINE
#define PD_JIGGLER_PATTERN_ENDING PD_JIGGLER_PATTERN_XLINE
#define PD_JIGGLER_AUTOSTOP
